# Generated by Django 4.2 on 2026-04-05 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_avatar_user_bio_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
